name: Auto Approve
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    # + pull request owner matches repository owner.
    # + pull request is not a draft
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Self Approve PR with Bot Token
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.TGTAKAOKA_BOT }}
          review-message: 'Self-approved as owner.'
